### ISSUE TITLE
能多个标注工具一起用吗，谢谢

### ISSUE THREAD

**Issue by xufengri** [open-mmlab/labelbee#159]

**Comment by Kerwin-L** [comment]
暂不支持哈，这边有个实验性的设计 `packages/lb-annotation/src/core/scheduler.ts` ，感兴趣可以看下：https://labelbee.github.io/?tool=polygonTool+rectTool （通过 ctrl + alt + shift + c 切换） ，该功能还不稳定，不推荐使用；
