### ISSUE TITLE
我写了一个将labelme的json文件转换为labelbee的json文件的脚本，可以给labelbee的代码做贡献吗？

### ISSUE THREAD

**Issue by Woshidawenxi** [open-mmlab/labelbee#249]
我写了一个将labelme的json文件转换为labelbee的json文件的脚本，可以给labelmebee的代码做贡献吗？https://github.com/Woshidawenxi/labelme2labelbee-json

**Comment by lihqi** [comment]
好强呀

**Comment by Woshidawenxi** [comment]
混子混子，哈哈哈
