### ISSUE TITLE
How to configure Sider in jsx？

### ISSUE THREAD

**Issue by mgsky1** [open-mmlab/labelbee#57]
hello, I am new to React. I want to configure sider bar in our project. I have read the documentation, noticing that the doc provides original Sider definition in TypeScript. In my project, I use jsx, so how to configure the Sider in jsx?
hello，我是react新手。我希望在自己的项目中自定义标注侧边栏。我阅读了文档，发现给出的是原始typescript的定义，想在demo中找侧边栏配置的例子但是没有找到，不知道如何在jsx中自定义侧边栏？

**Comment by Kerwin-L** [comment]
You can use it like below.

![image](https://user-images.githubusercontent.com/21312795/177073559-263080a7-cd3f-4806-bb6c-ae926aeeff74.png)


The `Sider` can use the `Components` in original `Sider Component`

 ![image](https://user-images.githubusercontent.com/21312795/177072904-4dc80b4a-afb9-4887-b063-d27429b7ba8a.png)

The location of how to use is here. There are indeed many usage gaps in the documentation, which we will continue to add~
https://github.com/open-mmlab/labelbee/blob/main/packages/lb-components/docs/annotation.md
